### ISSUE TITLE
Could you please add a license file?

### ISSUE THREAD

**Issue by brunosan** [alexeiabrahams/nighttime-lights#1]
To know the license, permitted uses and how to attribute (if not public domain or equivalent).

Thanks!

**Comment by alexeiabrahams** [comment]
Hi Bruno, thanks for your interest. ;) The research article to which this MATLAB script relates is accessible at my personal website: https://sites.google.com/site/alexeiabrahams2/

Please feel free to use and modify the code in whatever way you prefer, but be sure to cite the paper as follows:

Abrahams, A. and Lozano-Gracia, N. and Oram, C. J. 2016. "Deblurring nighttime lights". Working paper.

The BibTex citation is as follows:

@article
{alo2016,
   author={Abrahams, A. and Lozano-Gracia, N. and Oram, C. J.},
   title={Deblurring nighttime lights},
   journal={Working paper},
   volume={},
   year=2016,
   pages={}
}

**Comment by brunosan** [comment]
👍 Sent you a Pull request so it's part of the software.
